# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NunnLabContacts' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NunnLabContacts
  pod "StringSearchKit"

  target 'NunnLabContactsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NunnLabContactsUITests' do
    # Pods for testing
  end

end
